(function(){
"use strict";
function id(x){return document.getElementById(x)}
function lsget(k,d){try{var v=localStorage.getItem(LS+k);return v===null?d:v}catch(e){return d}}
function lsset(k,v){try{localStorage.setItem(LS+k,String(v))}catch(e){}}
function paceSec(s){var m=/^(\d{1,2}):([0-5]\d)$/.exec((s||"").trim());return m?(+m[1])*60+(+m[2]):NaN}
function paceTxt(sec){if(!isFinite(sec))return "—";sec=Math.round(sec);return String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function dur(mins){if(!isFinite(mins))return "—";var m=Math.round(mins),h=Math.floor(m/60);return h+"h "+String(m%60).padStart(2,"0")+"m"}
function dtx(d){if(isNaN(d.getTime()))return "—";return String(d.getMonth()+1).padStart(2,"0")+"/"+String(d.getDate()).padStart(2,"0")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}
function dirty(){id("dirty").textContent="有變更尚未 Apply";id("dirty").style.color="#a24d00";id("dirty").style.fontWeight="800"}
function clean(){id("dirty").textContent="已套用";id("dirty").style.color="";id("dirty").style.fontWeight=""}
function paceOptions(selected){var h="";for(var sec=240;sec<=720;sec+=5){var v=paceTxt(sec);h+='<option value="'+v+'"'+(v===selected?' selected':'')+'>'+v+' /km</option>'}return h}
function renderPaces(){var h="";ALL.forEach(function(r){var v=lsget("pace_"+r,"06:30");h+='<div class="paceCard"><b>'+r+'</b><br><label>基準配速 <select class="paceInput" data-runner="'+r+'">'+paceOptions(v)+'</select></label></div>'});id("paceCards").innerHTML=h}
function renderRows(){var h="";LEG_DATA.forEach(function(x){var c=x.car==="A"?"carA":"carB",gs=((x.leg-1)%5===0)?" group-start":"";h+='<tr class="'+c+gs+'" data-leg="'+x.leg+'" data-car="'+x.car+'" data-km="'+x.distance+'" data-default-runner="'+x.runner+'"><td><b>'+x.car+'</b></td><td><b>'+x.leg+'</b></td><td class="startAt c-start">—</td><td class="finishAt c-finish">—</td><td class="cumulative c-cum">—</td><td><select class="runnerSelect"></select></td><td>'+x.icon+'</td><td>'+x.difficulty+'</td><td>'+x.distance.toFixed(1)+'</td><td>+'+x.gain+'/-'+x.loss+'</td><td class="basePace">—</td><td><input class="adjust" type="number" value="0" step="5"> 秒</td><td class="effective">—</td><td class="runTime">—</td><td><input class="handoff" type="number" value="0" min="0"></td><td><input class="neutral" type="number" value="0" min="0"></td><td><a href="'+x.url+'" target="_blank" rel="noopener">路線 ↗</a><div class="coord">'+x.coord+'</div></td><td class="note">'+(x.note?'<span class="warn">注意</span> '+x.note:'')+'</td></tr>'});id("legsBody").innerHTML=h}
function renderGear(){id("gearList").innerHTML=GEAR.map(function(g,i){return '<label class="gear"><input type="checkbox" data-gear="'+i+'"><span><b>'+g[0]+'</b>｜'+g[1]+'</span></label>'}).join("")}
function renderOverview(){var h="";for(var g=0;g<6;g++){var car=g%2===0?"A":"B",s=g*5+1,e=s+4;h+='<div class="gbox"><div class="ghead '+car+'">'+car+' 車｜第 '+s+'–'+e+' 棒</div>';for(var l=s;l<=e;l++)h+='<div class="gline" data-mini="'+l+'"><b>#'+l+'</b><span class="miniRunner">—</span><span class="t miniStart">—</span><span>→</span><span class="t miniFinish">—</span><span class="cumMini muted miniCum">—</span></div>';h+='</div>'}id("groupOverview").innerHTML=h}
function restore(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){var l=tr.dataset.leg,sel=tr.querySelector(".runnerSelect"),cur=lsget("runner_"+l,tr.dataset.defaultRunner);sel.innerHTML="";MEMBERS[tr.dataset.car].forEach(function(r){var o=document.createElement("option");o.value=r;o.textContent=r;if(r===cur)o.selected=true;sel.appendChild(o)});tr.querySelector(".adjust").value=lsget("adj_"+l,"0");tr.querySelector(".handoff").value=lsget("handoff_"+l,"0");tr.querySelector(".neutral").value=lsget("neutral_"+l,"0")});id("raceStart").value=lsget("start","2026-09-19T04:00");document.querySelectorAll("[data-gear]").forEach(function(c){c.checked=lsget("gear_"+c.dataset.gear,"0")==="1"})}
function persist(el){if(el.id==="raceStart"){lsset("start",el.value);return}if(el.classList.contains("paceInput")){lsset("pace_"+el.dataset.runner,el.value);return}if(el.hasAttribute("data-gear")){lsset("gear_"+el.dataset.gear,el.checked?"1":"0");return}var tr=el.closest&&el.closest("tr[data-leg]");if(!tr)return;var l=tr.dataset.leg;if(el.classList.contains("runnerSelect"))lsset("runner_"+l,el.value);else if(el.classList.contains("adjust"))lsset("adj_"+l,el.value);else if(el.classList.contains("handoff"))lsset("handoff_"+l,el.value);else if(el.classList.contains("neutral"))lsset("neutral_"+l,el.value)}
function paces(){var m={};document.querySelectorAll(".paceInput").forEach(function(x){m[x.dataset.runner]=paceSec(x.value)});return m}
function calculate(){var start=new Date(id("raceStart").value);if(isNaN(start.getTime())){alert("請輸入有效起跑時間");return}var cur=new Date(start),off=0,neu=0,pm=paces();document.querySelectorAll("tr[data-leg]").forEach(function(tr){var r=tr.querySelector(".runnerSelect").value,base=pm[r],adj=Number(tr.querySelector(".adjust").value||0),eff=base+adj,km=Number(tr.dataset.km);var run=eff*km/60,w=Number(tr.querySelector(".handoff").value||0),n=Number(tr.querySelector(".neutral").value||0);tr.querySelector(".basePace").textContent=paceTxt(base);tr.querySelector(".effective").textContent=paceTxt(eff);tr.querySelector(".runTime").textContent=dur(run);tr.querySelector(".startAt").textContent=dtx(cur);cur=new Date(cur.getTime()+run*60000);off+=run;tr.querySelector(".finishAt").textContent=dtx(cur);tr.querySelector(".cumulative").textContent=dur((cur-start)/60000);var mini=document.querySelector('[data-mini="'+tr.dataset.leg+'"]');mini.querySelector(".miniRunner").textContent=r;mini.querySelector(".miniStart").textContent=tr.querySelector(".startAt").textContent;mini.querySelector(".miniFinish").textContent=tr.querySelector(".finishAt").textContent;mini.querySelector(".miniCum").textContent=tr.querySelector(".cumulative").textContent;cur=new Date(cur.getTime()+(w+n)*60000);off+=w;neu+=n});id("finishTime").textContent=dtx(cur);id("wallTime").textContent=dur((cur-start)/60000);id("officialTime").textContent=dur(off);id("neutralTime").textContent=dur(neu);clean()}
function bind(){document.querySelectorAll("input,select").forEach(function(el){el.addEventListener("input",function(){persist(el);dirty()});el.addEventListener("change",function(){persist(el);dirty()})});id("applyAll").onclick=calculate;id("resetAssign").onclick=function(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){var s=tr.querySelector(".runnerSelect");s.value=tr.dataset.defaultRunner;persist(s)});dirty()};id("resetTimes").onclick=function(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){["adjust","handoff","neutral"].forEach(function(c){var el=tr.querySelector("."+c);el.value=0;persist(el)})});dirty()}}
renderRows();renderPaces();renderGear();renderOverview();restore();bind();calculate()
})();