(function(){
"use strict";
function id(x){return document.getElementById(x)}
function lsget(k,d){try{var v=localStorage.getItem(LS+k);return v===null?d:v}catch(e){return d}}
function lsset(k,v){try{localStorage.setItem(LS+k,String(v))}catch(e){}}
function paceSec(s){var m=/^(\d{1,2}):([0-5]\d)$/.exec((s||"").trim());return m?(+m[1])*60+(+m[2]):NaN}
function paceTxt(sec){if(!isFinite(sec))return "—";sec=Math.round(sec);return String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function dur(mins){if(!isFinite(mins))return "—";var m=Math.round(mins),h=Math.floor(m/60);return h+"h "+String(m%60).padStart(2,"0")+"m"}
function dtx(d){if(isNaN(d.getTime()))return "—";return String(d.getMonth()+1).padStart(2,"0")+"/"+String(d.getDate()).padStart(2,"0")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}
function dirty(){id("dirty").textContent="有變更尚未 Apply";id("dirty").style.color="#a24d00";id("dirty").style.fontWeight="800"}
function clean(){id("dirty").textContent="已套用";id("dirty").style.color="";id("dirty").style.fontWeight=""}
function paceOptions(selected){var h="";for(var sec=240;sec<=720;sec+=5){var v=paceTxt(sec);h+='<option value="'+v+'"'+(v===selected?' selected':'')+'>'+v+' /km</option>'}return h}
function renderPaces(){var h="";ALL.forEach(function(r){var v=lsget("pace_"+r,"06:30");h+='<div class="paceCard"><b>'+r+'</b><br><label>基準配速 <select class="paceInput" data-runner="'+r+'">'+paceOptions(v)+'</select></label></div>'});id("paceCards").innerHTML=h}
function renderRows(){var h="";LEG_DATA.forEach(function(x){var c=x.car==="A"?"carA":"carB",gs=((x.leg-1)%5===0)?" group-start":"";h+='<tr class="'+c+gs+'" data-leg="'+x.leg+'" data-car="'+x.car+'" data-km="'+x.distance+'" data-default-runner="'+x.runner+'"><td><b>'+x.car+'</b></td><td><b>'+x.leg+'</b></td><td class="startAt c-start">—</td><td class="finishAt c-finish">—</td><td class="actualCell"><div class="actualWrap"><input class="actualArrival" type="datetime-local"><button type="button" class="setNow">現在</button><button type="button" class="clearActual">清除</button></div></td><td class="cumulative c-cum">—</td><td><select class="runnerSelect"></select></td><td>'+x.icon+'</td><td>'+x.difficulty+'</td><td>'+x.distance.toFixed(1)+'</td><td>+'+x.gain+'/-'+x.loss+'</td><td class="basePace">—</td><td><input class="adjust" type="number" value="0" step="5"> 秒</td><td class="effective">—</td><td class="runTime">—</td><td><input class="handoff" type="number" value="0" min="0"></td><td><input class="neutral" type="number" value="0" min="0"></td><td><a href="'+x.url+'" target="_blank" rel="noopener">路線 ↗</a><div class="coord">'+x.coord+'</div></td><td class="note">'+(x.note?'<span class="warn">注意</span> '+x.note:'')+'</td></tr>'});id("legsBody").innerHTML=h}
function renderGear(){id("gearList").innerHTML=GEAR.map(function(g,i){return '<label class="gear"><input type="checkbox" data-gear="'+i+'"><span><b>'+g[0]+'</b>｜'+g[1]+'</span></label>'}).join("")}
function renderOverview(){var h="";for(var g=0;g<6;g++){var car=g%2===0?"A":"B",s=g*5+1,e=s+4;h+='<div class="gbox"><div class="ghead '+car+'">'+car+' 車｜第 '+s+'–'+e+' 棒</div>';for(var l=s;l<=e;l++)h+='<div class="gline" data-mini="'+l+'"><b>#'+l+'</b><span class="miniRunner">—</span><span class="t miniStart">—</span><span>→</span><span class="t miniFinish">—</span><span class="cumMini muted miniCum">—</span></div>';h+='</div>'}id("groupOverview").innerHTML=h}
function restore(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){var l=tr.dataset.leg,sel=tr.querySelector(".runnerSelect"),cur=lsget("runner_"+l,tr.dataset.defaultRunner);sel.innerHTML="";MEMBERS[tr.dataset.car].forEach(function(r){var o=document.createElement("option");o.value=r;o.textContent=r;if(r===cur)o.selected=true;sel.appendChild(o)});tr.querySelector(".adjust").value=lsget("adj_"+l,"0");tr.querySelector(".handoff").value=lsget("handoff_"+l,"0");tr.querySelector(".neutral").value=lsget("neutral_"+l,"0");tr.querySelector(".actualArrival").value=lsget("actual_"+l,"")});id("raceStart").value=lsget("start","2026-09-19T04:00");document.querySelectorAll("[data-gear]").forEach(function(c){c.checked=lsget("gear_"+c.dataset.gear,"0")==="1"})}
function persist(el){if(el.id==="raceStart"){lsset("start",el.value);return}if(el.classList.contains("paceInput")){lsset("pace_"+el.dataset.runner,el.value);return}if(el.hasAttribute("data-gear")){lsset("gear_"+el.dataset.gear,el.checked?"1":"0");return}var tr=el.closest&&el.closest("tr[data-leg]");if(!tr)return;var l=tr.dataset.leg;if(el.classList.contains("runnerSelect"))lsset("runner_"+l,el.value);else if(el.classList.contains("adjust"))lsset("adj_"+l,el.value);else if(el.classList.contains("handoff"))lsset("handoff_"+l,el.value);else if(el.classList.contains("neutral"))lsset("neutral_"+l,el.value);else if(el.classList.contains("actualArrival"))lsset("actual_"+l,el.value)}
function paces(){var m={};document.querySelectorAll(".paceInput").forEach(function(x){m[x.dataset.runner]=paceSec(x.value)});return m}
var ROUTE_START=[24.3851389,120.7572222];
var routeMap=null,routeLine=null,currentMarker=null,checkpointLayer=null,CRUFU_SCHEDULE=[];
function localInputValue(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")+"T"+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}
function parseCoord(s){if(!s)return null;s=s.replace(/[’‘]/g,"'").replace(/[”″]/g,'"');var m=/(\d+)°(\d+)'([\d.]+)"?N\s+(\d+)°(\d+)'([\d.]+)"?E/.exec(s);if(!m)return null;return [Number(m[1])+Number(m[2])/60+Number(m[3])/3600,Number(m[4])+Number(m[5])/60+Number(m[6])/3600]}
function legPoint(leg){var p=parseCoord(LEG_DATA[leg-1].coord);return p||ROUTE_START}
function interp(a,b,f){f=Math.max(0,Math.min(1,f));return [a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]}
function initMap(){if(typeof L==="undefined"){id("currentStatus").textContent="地圖元件載入失敗";return}if(routeMap)return;var pts=[ROUTE_START];LEG_DATA.forEach(function(x){var p=parseCoord(x.coord);if(p)pts.push(p)});routeMap=L.map("routeMap",{zoomControl:true});L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(routeMap);routeLine=L.polyline(pts,{weight:4,opacity:.75}).addTo(routeMap);checkpointLayer=L.layerGroup().addTo(routeMap);L.circleMarker(ROUTE_START,{radius:5,weight:2,fillOpacity:.9}).bindPopup("起點｜三義").addTo(checkpointLayer);LEG_DATA.forEach(function(x){var p=parseCoord(x.coord);if(p)L.circleMarker(p,{radius:4,weight:1,fillOpacity:.8}).bindPopup("第 "+x.leg+" 棒終點").addTo(checkpointLayer)});currentMarker=L.circleMarker(ROUTE_START,{radius:9,weight:3,fillOpacity:1}).bindPopup("目前估計位置").addTo(routeMap);routeMap.fitBounds(routeLine.getBounds(),{padding:[20,20]})}
function updateCurrentStatus(){var now=new Date();id("systemNow").textContent=dtx(now);if(!CRUFU_SCHEDULE.length)return;var first=CRUFU_SCHEDULE[0],last=CRUFU_SCHEDULE[CRUFU_SCHEDULE.length-1],pos=ROUTE_START,status="尚未起跑",runner="—",leg="—";if(now<first.start){pos=ROUTE_START;status="尚未起跑"}else if(now>=last.waitEnd){pos=last.endCoord;status="已完成預估賽程"}else{for(var i=0;i<CRUFU_SCHEDULE.length;i++){var s=CRUFU_SCHEDULE[i];if(now>=s.start&&now<=s.anchorFinish){var denom=s.anchorFinish-s.start,frac=denom>0?(now-s.start)/denom:1;pos=interp(s.startCoord,s.endCoord,frac);status="跑步進行中";runner=s.runner;leg="#"+s.leg;break}if(now>s.anchorFinish&&now<s.waitEnd){pos=s.endCoord;status="交接 / 等待中";runner=s.runner;leg="#"+s.leg;break}}}id("currentStatus").textContent=status;id("currentRunner").textContent=runner;id("currentLeg").textContent=leg;if(currentMarker){currentMarker.setLatLng(pos);currentMarker.setPopupContent("<b>"+status+"</b><br>"+(leg!=="—"?leg+" "+runner:""))}}
function calculate(){var start=new Date(id("raceStart").value);if(isNaN(start.getTime())){alert("請輸入有效起跑時間");return}var cur=new Date(start),off=0,neu=0,pm=paces(),latest=null,schedule=[];document.querySelectorAll("tr[data-leg]").forEach(function(tr){var r=tr.querySelector(".runnerSelect").value,base=pm[r],adj=Number(tr.querySelector(".adjust").value||0),eff=base+adj,km=Number(tr.dataset.km);var run=eff*km/60,w=Number(tr.querySelector(".handoff").value||0),n=Number(tr.querySelector(".neutral").value||0);var leg=Number(tr.dataset.leg),startCoord=leg===1?ROUTE_START:legPoint(leg-1),endCoord=legPoint(leg);var legStart=new Date(cur),predFinish=new Date(cur.getTime()+run*60000);var actualInput=tr.querySelector(".actualArrival"),actual=actualInput.value?new Date(actualInput.value):null;if(actual&&isNaN(actual.getTime()))actual=null;tr.querySelector(".basePace").textContent=paceTxt(base);tr.querySelector(".effective").textContent=paceTxt(eff);tr.querySelector(".runTime").textContent=dur(run);tr.querySelector(".startAt").textContent=dtx(legStart);tr.querySelector(".finishAt").textContent=dtx(predFinish);var anchorFinish=actual||predFinish;tr.querySelector(".actualCell").classList.toggle("actualSet",!!actual);tr.querySelector(".cumulative").textContent=dur((anchorFinish-start)/60000);if(actual){var offset=Math.round((actual-predFinish)/60000);latest={leg:leg,runner:r,time:new Date(actual),offset:offset}}var mini=document.querySelector('[data-mini="'+tr.dataset.leg+'"]');mini.querySelector(".miniRunner").textContent=r;mini.querySelector(".miniStart").textContent=dtx(legStart);mini.querySelector(".miniFinish").textContent=dtx(anchorFinish)+(actual?" ✓":"");mini.querySelector(".miniCum").textContent=tr.querySelector(".cumulative").textContent;cur=new Date(anchorFinish.getTime()+(w+n)*60000);off+=run+w;neu+=n;schedule.push({leg:leg,runner:r,start:legStart,predFinish:predFinish,anchorFinish:new Date(anchorFinish),waitEnd:new Date(cur),startCoord:startCoord,endCoord:endCoord,actual:actual})});CRUFU_SCHEDULE=schedule;id("finishTime").textContent=dtx(cur);id("wallTime").textContent=dur((cur-start)/60000);id("officialTime").textContent=dur(off);id("neutralTime").textContent=dur(neu);if(latest){id("latestActual").textContent="#"+latest.leg+" "+latest.runner+" "+dtx(latest.time);id("latestOffset").textContent=(latest.offset>=0?"+":"")+latest.offset+" 分"}else{id("latestActual").textContent="尚未填寫";id("latestOffset").textContent="—"}clean();updateCurrentStatus()}
function csvCell(v){v=(v===null||v===undefined)?"":String(v);if(/[",\n\r]/.test(v))return '"'+v.replace(/"/g,'""')+'"';return v}
function exportCsv(){calculate();var rows=[];rows.push(["CRUFU 2026 西臺灣站","起跑時間",id("raceStart").value,"預估完賽",id("finishTime").textContent,"牆上總耗時",id("wallTime").textContent,"估計計時成績",id("officialTime").textContent,"官方中立等待",id("neutralTime").textContent]);rows.push([]);rows.push(["車","棒次","預估開始","預估結束","實際抵達","累積用時","跑者","時段","難度","距離(km)","爬升(m)","下降(m)","個人基準配速","棒次修正(秒/km)","採用配速","跑步用時","交接等待(分)","官方中立(分)","官方路線","座標","提醒"]);document.querySelectorAll("tr[data-leg]").forEach(function(tr){var leg=Number(tr.dataset.leg),x=LEG_DATA[leg-1];rows.push([tr.dataset.car,leg,tr.querySelector(".startAt").textContent,tr.querySelector(".finishAt").textContent,tr.querySelector(".actualArrival").value,tr.querySelector(".cumulative").textContent,tr.querySelector(".runnerSelect").value,x.icon,x.difficulty,x.distance,x.gain,x.loss,tr.querySelector(".basePace").textContent,tr.querySelector(".adjust").value,tr.querySelector(".effective").textContent,tr.querySelector(".runTime").textContent,tr.querySelector(".handoff").value,tr.querySelector(".neutral").value,x.url,x.coord,x.note||""])});rows.push([]);rows.push(["個人基準配速"]);rows.push(["跑者","配速"]);ALL.forEach(function(r){var el=document.querySelector('.paceInput[data-runner="'+r+'"]');rows.push([r,el?el.value:""])});rows.push([]);rows.push(["攜帶物品 Checklist"]);rows.push(["分類","項目","已勾選"]);GEAR.forEach(function(g,i){var c=document.querySelector('[data-gear="'+i+'"]');rows.push([g[0],g[1],c&&c.checked?"是":"否"])});var csv="\uFEFF"+rows.map(function(r){return r.map(csvCell).join(",")}).join("\r\n");var blob=new Blob([csv],{type:"text/csv;charset=utf-8"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="CRUFU_2026_西臺灣站_時間表_"+new Date().toISOString().slice(0,10)+".csv";document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(url);a.remove()},1000)}
function bind(){document.querySelectorAll("input,select").forEach(function(el){el.addEventListener("input",function(){persist(el);dirty()});el.addEventListener("change",function(){persist(el);dirty();if(el.classList.contains("actualArrival"))calculate()})});document.querySelectorAll(".setNow").forEach(function(btn){btn.onclick=function(){var tr=btn.closest("tr[data-leg]"),el=tr.querySelector(".actualArrival");el.value=localInputValue(new Date());persist(el);calculate()}});document.querySelectorAll(".clearActual").forEach(function(btn){btn.onclick=function(){var tr=btn.closest("tr[data-leg]"),el=tr.querySelector(".actualArrival");el.value="";persist(el);calculate()}});id("applyAll").onclick=calculate;id("exportCsv").onclick=exportCsv;id("resetAssign").onclick=function(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){var s=tr.querySelector(".runnerSelect");s.value=tr.dataset.defaultRunner;persist(s)});dirty()};id("resetTimes").onclick=function(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){["adjust","handoff","neutral"].forEach(function(c){var el=tr.querySelector("."+c);el.value=0;persist(el)})});dirty()}}
renderRows();renderPaces();renderGear();renderOverview();restore();bind();initMap();calculate();setInterval(updateCurrentStatus,15000)
})();