(function(){
"use strict";
function id(x){return document.getElementById(x)}
function lsget(k,d){try{var v=localStorage.getItem(LS+k);return v===null?d:v}catch(e){return d}}
function lsset(k,v){try{localStorage.setItem(LS+k,String(v))}catch(e){}}
function paceSec(s){var m=/^(\d{1,2}):([0-5]\d)$/.exec((s||"").trim());return m?(+m[1])*60+(+m[2]):NaN}
function paceTxt(sec){if(!isFinite(sec))return "—";sec=Math.round(sec);return String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0")}
function dur(mins){if(!isFinite(mins))return "—";var m=Math.round(mins),h=Math.floor(m/60);return h+"h "+String(m%60).padStart(2,"0")+"m"}
function dtx(d){if(isNaN(d.getTime()))return "—";return String(d.getMonth()+1).padStart(2,"0")+"/"+String(d.getDate()).padStart(2,"0")+" "+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}
function dirty(){id("dirty").textContent="有變更尚未 Apply";id("dirty").style.color="#a24d00";id("dirty").style.fontWeight="800"}
function clean(){id("dirty").textContent="已套用";id("dirty").style.color="";id("dirty").style.fontWeight=""}
function paceOptions(selected){var h="";for(var sec=240;sec<=720;sec+=5){var v=paceTxt(sec);h+='<option value="'+v+'"'+(v===selected?' selected':'')+'>'+v+' /km</option>'}return h}
function renderPaces(){var h="";ALL.forEach(function(r){var v=lsget("pace_"+r,"06:30");h+='<div class="paceCard"><b>'+r+'</b><br><label>基準配速 <select class="paceInput" data-runner="'+r+'">'+paceOptions(v)+'</select></label></div>'});id("paceCards").innerHTML=h}
function renderRows(){var h="";LEG_DATA.forEach(function(x){var c=x.car==="A"?"carA":"carB",gs=((x.leg-1)%5===0)?" group-start":"";h+='<tr class="'+c+gs+'" data-leg="'+x.leg+'" data-car="'+x.car+'" data-km="'+x.distance+'" data-default-runner="'+x.runner+'"><td><b>'+x.car+'</b></td><td><b>'+x.leg+'</b></td><td><select class="runnerSelect"></select></td><td class="startAt c-start">—</td><td class="finishAt c-finish">—</td><td class="cumulative c-cum">—</td><td>'+x.icon+'</td><td class="actualCell"><div class="actualWrap"><input class="actualArrival" type="datetime-local"><button type="button" class="setNow">現在</button><button type="button" class="clearActual">清除</button></div></td><td>'+x.difficulty+'</td><td>'+x.distance.toFixed(1)+'</td><td>+'+x.gain+'/-'+x.loss+'</td><td class="basePace">—</td><td><input class="adjust" type="number" value="0" step="5"> 秒</td><td class="effective">—</td><td class="runTime">—</td><td><input class="handoff" type="number" value="0" min="0"></td><td><input class="neutral" type="number" value="0" min="0"></td><td><a href="'+x.url+'" target="_blank" rel="noopener">路線 ↗</a><div class="coord">'+x.coord+'</div></td><td class="note">'+(x.note?'<span class="warn">注意</span> '+x.note:'')+'</td></tr>'});id("legsBody").innerHTML=h}
function renderGear(){id("gearList").innerHTML=GEAR.map(function(g,i){return '<label class="gear"><input type="checkbox" data-gear="'+i+'"><span><b>'+g[0]+'</b>｜'+g[1]+'</span></label>'}).join("")}
function renderOverview(){var h="";for(var g=0;g<6;g++){var car=g%2===0?"A":"B",s=g*5+1,e=s+4;h+='<div class="gbox"><div class="ghead '+car+'">'+car+' 車｜第 '+s+'–'+e+' 棒</div>';for(var l=s;l<=e;l++)h+='<div class="gline" data-mini="'+l+'"><b>#'+l+'</b><span class="miniRunner">—</span><span class="t miniStart">—</span><span>→</span><span class="t miniFinish">—</span><span class="cumMini muted miniCum">—</span></div>';h+='</div>'}id("groupOverview").innerHTML=h}
function restore(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){var l=tr.dataset.leg,sel=tr.querySelector(".runnerSelect"),cur=lsget("runner_"+l,tr.dataset.defaultRunner);sel.innerHTML="";MEMBERS[tr.dataset.car].forEach(function(r){var o=document.createElement("option");o.value=r;o.textContent=r;if(r===cur)o.selected=true;sel.appendChild(o)});tr.querySelector(".adjust").value=lsget("adj_"+l,"0");tr.querySelector(".handoff").value=lsget("handoff_"+l,"0");tr.querySelector(".neutral").value=lsget("neutral_"+l,"0");tr.querySelector(".actualArrival").value=lsget("actual_"+l,"")});id("raceStart").value=lsget("start","2026-09-19T04:00");document.querySelectorAll("[data-gear]").forEach(function(c){c.checked=lsget("gear_"+c.dataset.gear,"0")==="1"})}
function persist(el){if(el.id==="raceStart"){lsset("start",el.value);return}if(el.classList.contains("paceInput")){lsset("pace_"+el.dataset.runner,el.value);return}if(el.hasAttribute("data-gear")){lsset("gear_"+el.dataset.gear,el.checked?"1":"0");return}var tr=el.closest&&el.closest("tr[data-leg]");if(!tr)return;var l=tr.dataset.leg;if(el.classList.contains("runnerSelect"))lsset("runner_"+l,el.value);else if(el.classList.contains("adjust"))lsset("adj_"+l,el.value);else if(el.classList.contains("handoff"))lsset("handoff_"+l,el.value);else if(el.classList.contains("neutral"))lsset("neutral_"+l,el.value);else if(el.classList.contains("actualArrival"))lsset("actual_"+l,el.value)}
function paces(){var m={};document.querySelectorAll(".paceInput").forEach(function(x){m[x.dataset.runner]=paceSec(x.value)});return m}
var ROUTE_START=[24.3851389,120.7572222];
var routeMap=null,routeLine=null,currentMarker=null,checkpointLayer=null,confirmedLayer=null,estimatedLayer=null,CRUFU_SCHEDULE=[];
function localInputValue(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")+"T"+String(d.getHours()).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")}
function trackFor(leg){return (window.ROUTE_TRACKS&&window.ROUTE_TRACKS[String(leg)])||null}
function legTrackDistance(leg){var t=trackFor(leg);return t&&isFinite(t.distance_km)?Number(t.distance_km):Number(LEG_DATA[leg-1].distance||0)}
function totalTrackDistance(){var n=0;for(var i=1;i<=LEG_DATA.length;i++)n+=legTrackDistance(i);return n}
function sumTrackDistanceThrough(leg){var n=0;for(var i=1;i<=leg;i++)n+=legTrackDistance(i);return n}
function pointAlongTrack(leg,fraction){var t=trackFor(leg);if(!t||!t.points||!t.points.length){var fallback=LEG_DATA[leg-1];return fallback&&fallback.coord?parseCoord(fallback.coord):ROUTE_START}fraction=Math.max(0,Math.min(1,fraction));var cum=t.cum_km||[],pts=t.points,target=(Number(t.distance_km)||cum[cum.length-1]||0)*fraction;if(!cum.length||cum.length!==pts.length)return pts[Math.min(pts.length-1,Math.round((pts.length-1)*fraction))];var lo=0,hi=cum.length-1;while(lo<hi){var mid=Math.floor((lo+hi)/2);if(cum[mid]<target)lo=mid+1;else hi=mid}var i=lo;if(i<=0)return pts[0];if(i>=pts.length)return pts[pts.length-1];var a=cum[i-1],b=cum[i],span=b-a,ff=span>0?(target-a)/span:0;return [pts[i-1][0]+(pts[i][0]-pts[i-1][0])*ff,pts[i-1][1]+(pts[i][1]-pts[i-1][1])*ff]}
function partialTrackPoints(leg,fraction){var t=trackFor(leg);if(!t||!t.points||!t.points.length)return [];fraction=Math.max(0,Math.min(1,fraction));if(fraction<=0)return [t.points[0]];if(fraction>=1)return t.points.slice();var cum=t.cum_km,target=(Number(t.distance_km)||cum[cum.length-1]||0)*fraction,out=[];for(var i=0;i<t.points.length;i++){if(cum[i]<=target)out.push(t.points[i]);else {out.push(pointAlongTrack(leg,fraction));break}}return out}
function parseCoord(s){if(!s)return null;s=s.replace(/[’‘]/g,"'").replace(/[”″]/g,'"');var m=/(\d+)°(\d+)'([\d.]+)"?N\s+(\d+)°(\d+)'([\d.]+)"?E/.exec(s);if(!m)return null;return [Number(m[1])+Number(m[2])/60+Number(m[3])/3600,Number(m[4])+Number(m[5])/60+Number(m[6])/3600]}
function latestActualRecord(){var latest=null;document.querySelectorAll("tr[data-leg]").forEach(function(tr){var el=tr.querySelector(".actualArrival");if(el&&el.value){var d=new Date(el.value);if(!isNaN(d.getTime()))latest={leg:Number(tr.dataset.leg),time:d,runner:tr.querySelector(".runnerSelect").value}}});return latest}
function initMap(){var statusEl=id("routeDataStatus"),routeCount=window.ROUTE_TRACKS?Object.keys(window.ROUTE_TRACKS).length:0;if(statusEl)statusEl.textContent=routeCount+"/30 棒";if(typeof L==="undefined"){id("currentStatus").textContent="地圖元件未載入";if(statusEl)statusEl.textContent=routeCount+"/30 棒｜Leaflet 未載入";return}if(routeMap)return;try{routeMap=L.map("routeMap",{zoomControl:true});L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(routeMap);checkpointLayer=L.layerGroup().addTo(routeMap);confirmedLayer=L.layerGroup().addTo(routeMap);estimatedLayer=L.layerGroup().addTo(routeMap);var all=[];for(var leg=1;leg<=LEG_DATA.length;leg++){var t=trackFor(leg);if(t&&t.points&&t.points.length){all=all.concat(t.points);L.circleMarker(t.points[t.points.length-1],{radius:3,weight:1,fillOpacity:.75,color:"#374151"}).bindPopup("第 "+leg+" 棒終點").addTo(checkpointLayer)}}if(all.length){routeLine=L.polyline(all,{color:"#d92d20",weight:6,opacity:.95}).addTo(routeMap);routeMap.fitBounds(routeLine.getBounds(),{padding:[18,18]});if(statusEl)statusEl.textContent=routeCount+"/30 棒｜"+all.length+" 軌跡點"}else{id("currentStatus").textContent="GPS 軌跡資料為空";if(statusEl)statusEl.textContent="0/30 棒｜無軌跡點"}currentMarker=L.circleMarker(all.length?all[0]:ROUTE_START,{radius:9,weight:3,fillOpacity:1,color:"#111827",fillColor:"#facc15"}).bindPopup("目前估計位置").addTo(routeMap)}catch(e){id("currentStatus").textContent="地圖繪製錯誤";if(statusEl)statusEl.textContent=routeCount+"/30 棒｜"+e.message;console.error("CRUFU map init failed",e)}}
function drawProgress(latest,currentLeg,currentFrac){if(!routeMap)return;confirmedLayer.clearLayers();estimatedLayer.clearLayers();if(latest){for(var leg=1;leg<=latest.leg;leg++){var t=trackFor(leg);if(t&&t.points)L.polyline(t.points,{color:"#087f5b",weight:7,opacity:.95}).addTo(confirmedLayer)}}var from=latest?latest.leg+1:1;if(currentLeg>=from){for(var l=from;l<currentLeg;l++){var t2=trackFor(l);if(t2&&t2.points)L.polyline(t2.points,{color:"#2563eb",weight:6,opacity:.9,dashArray:"8 6"}).addTo(estimatedLayer)}var pp=partialTrackPoints(currentLeg,currentFrac);if(pp.length>1)L.polyline(pp,{color:"#2563eb",weight:6,opacity:.95,dashArray:"8 6"}).addTo(estimatedLayer)}}
function updateCurrentStatus(){var now=new Date();id("systemNow").textContent=dtx(now);if(!CRUFU_SCHEDULE.length)return;var total=totalTrackDistance(),latest=latestActualRecord(),confirmed=latest?sumTrackDistanceThrough(latest.leg):0;var estimated=confirmed,pos=latest?pointAlongTrack(latest.leg,1):pointAlongTrack(1,0),status=latest?"等待下一棒":"尚未起跑",runner="—",legTxt="—",currentLeg=0,currentFrac=0;var fromLeg=latest?latest.leg+1:1;if(latest)id("confirmedLeg").textContent="#"+latest.leg+" "+latest.runner;else id("confirmedLeg").textContent="尚無";for(var i=0;i<CRUFU_SCHEDULE.length;i++){var s=CRUFU_SCHEDULE[i];if(s.leg<fromLeg)continue;if(now<s.start){status=(latest?"最新實際抵達後等待 / 尚未出發":"尚未起跑");break}if(now>=s.start&&now<=s.anchorFinish){var denom=s.anchorFinish-s.start,frac=denom>0?(now-s.start)/denom:1;currentLeg=s.leg;currentFrac=Math.max(0,Math.min(1,frac));estimated=sumTrackDistanceThrough(s.leg-1)+legTrackDistance(s.leg)*currentFrac;pos=pointAlongTrack(s.leg,currentFrac);status="跑步進行中";runner=s.runner;legTxt="#"+s.leg;break}if(now>s.anchorFinish&&now<s.waitEnd){currentLeg=s.leg;currentFrac=1;estimated=sumTrackDistanceThrough(s.leg);pos=pointAlongTrack(s.leg,1);status="交接 / 等待中";runner=s.runner;legTxt="#"+s.leg;break}estimated=sumTrackDistanceThrough(s.leg);pos=pointAlongTrack(s.leg,1);currentLeg=s.leg;currentFrac=1}if(now>=CRUFU_SCHEDULE[CRUFU_SCHEDULE.length-1].waitEnd){status="已完成預估賽程";runner="—";legTxt="#30";estimated=total;pos=pointAlongTrack(30,1)}estimated=Math.max(confirmed,Math.min(total,estimated));id("currentStatus").textContent=status;id("currentRunner").textContent=runner;id("currentLeg").textContent=legTxt;id("confirmedKm").textContent=confirmed.toFixed(1)+" km";id("estimatedKm").textContent=estimated.toFixed(1)+" km";id("remainingKm").textContent=Math.max(0,total-estimated).toFixed(1)+" km";if(currentMarker){currentMarker.setLatLng(pos);currentMarker.setPopupContent("<b>"+status+"</b><br>"+(legTxt!=="—"?legTxt+" "+runner:"")+"<br>估計完成 "+estimated.toFixed(1)+" / "+total.toFixed(1)+" km")}drawProgress(latest,currentLeg,currentFrac)}
function calculate(){var start=new Date(id("raceStart").value);if(isNaN(start.getTime())){alert("請輸入有效起跑時間");return}var cur=new Date(start),off=0,neu=0,pm=paces(),latest=null,schedule=[];document.querySelectorAll("tr[data-leg]").forEach(function(tr){var r=tr.querySelector(".runnerSelect").value,base=pm[r],adj=Number(tr.querySelector(".adjust").value||0),eff=base+adj,km=Number(tr.dataset.km);var run=eff*km/60,w=Number(tr.querySelector(".handoff").value||0),n=Number(tr.querySelector(".neutral").value||0);var leg=Number(tr.dataset.leg),startCoord=pointAlongTrack(leg,0),endCoord=pointAlongTrack(leg,1);var legStart=new Date(cur),predFinish=new Date(cur.getTime()+run*60000);var actualInput=tr.querySelector(".actualArrival"),actual=actualInput.value?new Date(actualInput.value):null;if(actual&&isNaN(actual.getTime()))actual=null;tr.querySelector(".basePace").textContent=paceTxt(base);tr.querySelector(".effective").textContent=paceTxt(eff);tr.querySelector(".runTime").textContent=dur(run);tr.querySelector(".startAt").textContent=dtx(legStart);tr.querySelector(".finishAt").textContent=dtx(predFinish);var anchorFinish=actual||predFinish;tr.querySelector(".actualCell").classList.toggle("actualSet",!!actual);tr.querySelector(".cumulative").textContent=dur((anchorFinish-start)/60000);if(actual){var offset=Math.round((actual-predFinish)/60000);latest={leg:leg,runner:r,time:new Date(actual),offset:offset}}var mini=document.querySelector('[data-mini="'+tr.dataset.leg+'"]');mini.querySelector(".miniRunner").textContent=r;mini.querySelector(".miniStart").textContent=dtx(legStart);mini.querySelector(".miniFinish").textContent=dtx(anchorFinish)+(actual?" ✓":"");mini.querySelector(".miniCum").textContent=tr.querySelector(".cumulative").textContent;cur=new Date(anchorFinish.getTime()+(w+n)*60000);off+=run+w;neu+=n;schedule.push({leg:leg,runner:r,start:legStart,predFinish:predFinish,anchorFinish:new Date(anchorFinish),waitEnd:new Date(cur),startCoord:startCoord,endCoord:endCoord,actual:actual})});CRUFU_SCHEDULE=schedule;id("finishTime").textContent=dtx(cur);id("wallTime").textContent=dur((cur-start)/60000);id("officialTime").textContent=dur(off);id("neutralTime").textContent=dur(neu);if(latest){id("latestActual").textContent="#"+latest.leg+" "+latest.runner+" "+dtx(latest.time);id("latestOffset").textContent=(latest.offset>=0?"+":"")+latest.offset+" 分"}else{id("latestActual").textContent="尚未填寫";id("latestOffset").textContent="—"}clean();updateCurrentStatus()}
function csvCell(v){v=(v===null||v===undefined)?"":String(v);if(/[",\n\r]/.test(v))return '"'+v.replace(/"/g,'""')+'"';return v}
function exportCsv(){calculate();var rows=[];rows.push(["CRUFU 2026 西臺灣站","起跑時間",id("raceStart").value,"預估完賽",id("finishTime").textContent,"牆上總耗時",id("wallTime").textContent,"估計計時成績",id("officialTime").textContent,"官方中立等待",id("neutralTime").textContent]);rows.push([]);rows.push(["車","棒次","跑者","預估開始","預估結束","累積用時","時段","實際抵達","難度","距離(km)","爬升(m)","下降(m)","個人基準配速","棒次修正(秒/km)","採用配速","跑步用時","交接等待(分)","官方中立(分)","官方路線","座標","提醒"]);document.querySelectorAll("tr[data-leg]").forEach(function(tr){var leg=Number(tr.dataset.leg),x=LEG_DATA[leg-1];rows.push([tr.dataset.car,leg,tr.querySelector(".runnerSelect").value,tr.querySelector(".startAt").textContent,tr.querySelector(".finishAt").textContent,tr.querySelector(".cumulative").textContent,x.icon,tr.querySelector(".actualArrival").value,x.difficulty,x.distance,x.gain,x.loss,tr.querySelector(".basePace").textContent,tr.querySelector(".adjust").value,tr.querySelector(".effective").textContent,tr.querySelector(".runTime").textContent,tr.querySelector(".handoff").value,tr.querySelector(".neutral").value,x.url,x.coord,x.note||""])});rows.push([]);rows.push(["個人基準配速"]);rows.push(["跑者","配速"]);ALL.forEach(function(r){var el=document.querySelector('.paceInput[data-runner="'+r+'"]');rows.push([r,el?el.value:""])});rows.push([]);rows.push(["攜帶物品 Checklist"]);rows.push(["分類","項目","已勾選"]);GEAR.forEach(function(g,i){var c=document.querySelector('[data-gear="'+i+'"]');rows.push([g[0],g[1],c&&c.checked?"是":"否"])});var csv="\uFEFF"+rows.map(function(r){return r.map(csvCell).join(",")}).join("\r\n");var blob=new Blob([csv],{type:"text/csv;charset=utf-8"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="CRUFU_2026_西臺灣站_時間表_"+new Date().toISOString().slice(0,10)+".csv";document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(url);a.remove()},1000)}
function bind(){document.querySelectorAll("input,select").forEach(function(el){el.addEventListener("input",function(){persist(el);dirty()});el.addEventListener("change",function(){persist(el);dirty();if(el.classList.contains("actualArrival"))calculate()})});document.querySelectorAll(".setNow").forEach(function(btn){btn.onclick=function(){var tr=btn.closest("tr[data-leg]"),el=tr.querySelector(".actualArrival");el.value=localInputValue(new Date());persist(el);calculate()}});document.querySelectorAll(".clearActual").forEach(function(btn){btn.onclick=function(){var tr=btn.closest("tr[data-leg]"),el=tr.querySelector(".actualArrival");el.value="";persist(el);calculate()}});id("applyAll").onclick=calculate;id("exportCsv").onclick=exportCsv;id("resetAssign").onclick=function(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){var s=tr.querySelector(".runnerSelect");s.value=tr.dataset.defaultRunner;persist(s)});dirty()};id("resetTimes").onclick=function(){document.querySelectorAll("tr[data-leg]").forEach(function(tr){["adjust","handoff","neutral"].forEach(function(c){var el=tr.querySelector("."+c);el.value=0;persist(el)})});dirty()}}
renderRows();renderPaces();renderGear();renderOverview();restore();bind();initMap();calculate();setInterval(updateCurrentStatus,15000)
})();